// `font` is a Google Fonts family name (must support italic — the storefront
// leans on italic display type throughout) used for storefront headings.
// `radius` is the card-corner roundness in px, applied via a CSS variable in
// StorefrontPreview.jsx — pill/circular shapes (nav, CTAs, category circles)
// stay round regardless of theme.
export const THEMES = {
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean and modern with lots of white space',
    ink: '#1e293b',
    accent: '#4166F5',
    soft: '#F8F4E8',
    font: 'Inter',
    radius: 16,
  },
  bold: {
    id: 'bold',
    name: 'Bold',
    description: 'High contrast with strong colours and striking typography',
    ink: '#0f172a',
    accent: '#ea580c',
    soft: '#fef2f2',
    font: 'Archivo',
    radius: 8,
  },
  elegant: {
    id: 'elegant',
    name: 'Elegant',
    description: 'Refined serif fonts and muted tones for a premium feel',
    ink: '#292524',
    accent: '#7c3aed',
    soft: '#f5f3ff',
    font: 'Playfair Display',
    radius: 4,
  },
  playful: {
    id: 'playful',
    name: 'Playful',
    description: 'Bright colours and rounded corners for a friendly look',
    ink: '#1e293b',
    accent: '#db2777',
    soft: '#fdf2f8',
    font: 'Poppins',
    radius: 28,
  },
  earthy: {
    id: 'earthy',
    name: 'Earthy',
    description: 'Warm, organic tones inspired by nature',
    ink: '#1c1917',
    accent: '#059669',
    soft: '#f0fdf4',
    font: 'Merriweather',
    radius: 20,
  },
  luxury: {
    id: 'luxury',
    name: 'Luxury',
    description: 'Black and gold with a sharp, premium edge',
    ink: '#1a1a1a',
    accent: '#C9A227',
    soft: '#FAF7F0',
    font: 'Cormorant Garamond',
    radius: 2,
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean',
    description: 'Breezy blues and teals for a fresh, coastal feel',
    ink: '#0c2d48',
    accent: '#0891b2',
    soft: '#ecfeff',
    font: 'Nunito',
    radius: 24,
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    description: 'Warm oranges on a soft glow, easygoing and inviting',
    ink: '#451a03',
    accent: '#f97316',
    soft: '#fff7ed',
    font: 'DM Serif Display',
    radius: 20,
  },
  monochrome: {
    id: 'monochrome',
    name: 'Monochrome',
    description: 'Pure grayscale for a sharp, architectural look',
    ink: '#111111',
    accent: '#525252',
    soft: '#fafafa',
    font: 'Space Grotesk',
    radius: 6,
  },
  vintage: {
    id: 'vintage',
    name: 'Vintage',
    description: 'Sepia tones and classic serif for a timeless feel',
    ink: '#3f2e1e',
    accent: '#a16207',
    soft: '#fdf6ec',
    font: 'Libre Baskerville',
    radius: 10,
  },
  tropical: {
    id: 'tropical',
    name: 'Tropical',
    description: 'Vivid coral and green, playful and full of energy',
    ink: '#064e3b',
    accent: '#fb7185',
    soft: '#f0fdfa',
    font: 'Baloo 2',
    radius: 32,
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    description: 'Deep indigo tones with a sleek, modern typeface',
    ink: '#030712',
    accent: '#6366f1',
    soft: '#eef2ff',
    font: 'Sora',
    radius: 14,
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    description: 'Deep greens and warm cream — natural, grounded, organic',
    ink: '#14532d',
    accent: '#16a34a',
    soft: '#f0fdf4',
    font: 'Lora',
    radius: 12,
  },
  // NOTE: an existing 'ocean' key/id above already covers a "breezy coastal
  // blues" preset. The plan for this round specified a second, distinct
  // "Ocean" preset (navy/teal, calm-trustworthy) — since object keys and
  // theme ids must be unique, it's added here as 'deepOcean' with the name
  // "Deep Ocean" (same colours/values the plan specified) instead of
  // silently overwriting the pre-existing 'ocean' entry.
  deepOcean: {
    id: 'deepOcean',
    name: 'Deep Ocean',
    description: 'Navy and teal over cool white — calm and trustworthy',
    ink: '#0c4a6e',
    accent: '#0d9488',
    soft: '#f0f9ff',
    font: 'Inter',
    radius: 16,
  },
  blush: {
    id: 'blush',
    name: 'Blush',
    description: 'Rose and charcoal — soft, warm, beauty-forward',
    ink: '#3f3f46',
    accent: '#e11d48',
    soft: '#fff1f2',
    font: 'Playfair Display',
    radius: 20,
  },
  noir: {
    id: 'noir',
    name: 'Noir',
    description: 'Black, gold accents — premium night-mode luxury',
    ink: '#111111',
    accent: '#ca8a04',
    soft: '#fafaf9',
    font: 'Archivo',
    radius: 2,
  },
}

// Broader font list for the custom-override dropdown — includes every theme
// font above plus a few extra well-paired Google Fonts (all support italic).
export const FONT_OPTIONS = [
  { id: 'inter', label: 'Inter', family: 'Inter' },
  { id: 'archivo', label: 'Archivo', family: 'Archivo' },
  { id: 'playfair-display', label: 'Playfair Display', family: 'Playfair Display' },
  { id: 'poppins', label: 'Poppins', family: 'Poppins' },
  { id: 'merriweather', label: 'Merriweather', family: 'Merriweather' },
  { id: 'cormorant-garamond', label: 'Cormorant Garamond', family: 'Cormorant Garamond' },
  { id: 'nunito', label: 'Nunito', family: 'Nunito' },
  { id: 'dm-serif-display', label: 'DM Serif Display', family: 'DM Serif Display' },
  { id: 'space-grotesk', label: 'Space Grotesk', family: 'Space Grotesk' },
  { id: 'libre-baskerville', label: 'Libre Baskerville', family: 'Libre Baskerville' },
  { id: 'baloo-2', label: 'Baloo 2', family: 'Baloo 2' },
  { id: 'sora', label: 'Sora', family: 'Sora' },
  { id: 'lora', label: 'Lora', family: 'Lora' },
  { id: 'josefin-sans', label: 'Josefin Sans', family: 'Josefin Sans' },
  { id: 'crimson-text', label: 'Crimson Text', family: 'Crimson Text' },
  { id: 'fraunces', label: 'Fraunces', family: 'Fraunces' },
  { id: 'outfit', label: 'Outfit', family: 'Outfit' },
  { id: 'quicksand', label: 'Quicksand', family: 'Quicksand' },
]

// Named shape presets for the custom-override radius picker.
export const RADIUS_OPTIONS = [
  { id: 'sharp', label: 'Sharp', value: 6 },
  { id: 'soft', label: 'Soft', value: 16 },
  { id: 'round', label: 'Round', value: 28 },
]
